# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('episode', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('synopsys', models.CharField(max_length=200)),
                ('audience', models.CharField(max_length=200, null=True)),
                ('primo_url', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('entry_id', models.CharField(max_length=50)),
                ('video_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('from_year', models.SmallIntegerField(null=True)),
                ('to_year', models.SmallIntegerField(null=True)),
                ('genre', models.ManyToManyField(blank=True, related_name='appears_in_series', to='video.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Series'),
        ),
        migrations.AddField(
            model_name='asset',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='appears_in_assets', to='video.Genre'),
        ),
        migrations.AddField(
            model_name='asset',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Season'),
        ),
        migrations.AddField(
            model_name='asset',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Series'),
        ),
    ]
