# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20151125_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='from_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='to_year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
